apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
    - name: "8443"
      port: 8443
      targetPort: 8443
  selector:
    io.kompose.service: app
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      initContainers:
        - name: init
          image: alpine:3
          command: ["/bin/sh", "-c"]
          args:
            - chown 1000:1000 /sock;
              chown 1000:1000 /tmp/appdata;
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /sock
              name: sockdata
            - mountPath: /tmp/appdata
              name: appdata
      containers:
        # TODO: need to patch this image to use the correct tag
        - image: henrytrantdt/magento-nginx:main
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 8000
            - containerPort: 8443
          resources: {}
          volumeMounts:
            - name: ssldata
              mountPath: /etc/nginx/certs
              readOnly: true
            - mountPath: /sock
              name: sockdata
            - mountPath: /tmp/appdata
              name: appdata
            - mountPath: /var/www/html/auth.json
              subPath: auth.json
              name: composerauth
            - mountPath: /var/www/html/app/etc/env.php
              subPath: env.php
              name: appenv
            - mountPath: /var/www/html/app/etc/config.php
              subPath: config.php
              name: appconfig
      restartPolicy: Always
      volumes:
        - name: sockdata
          persistentVolumeClaim:
            claimName: sockdata
        - name: appdata
          persistentVolumeClaim:
            claimName: appdata
        - name: ssldata
          configMap:
            defaultMode: 0400
            name: ssldata
            items:
              - key: sslcert
                path: nginx.crt
              - key: sslkey
                path: nginx.key
        - name: composerauth
          configMap:
            name: composerauth
            items:
              - key: auth
                path: auth.json
        - name: appconfig
          configMap:
            name: appconfig
            defaultMode: 0664
            items:
              - key: config
                path: config.php
        - name: appenv
          configMap:
            name: appenv
            defaultMode: 0664
            items:
              - key: env
                path: env.php
