apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
    - name: "8443"
      port: 8443
      targetPort: 8443
  selector:
    io.kompose.service: app
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      initContainers:
        - name: init
          image: alpine:3
          command: ["/bin/sh", "-c"]
          args:
            - touch /var/www/test_chown.txt
              chown 1000:1000 /var/www/test_chown.txt
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /sock
              name: sockdata
            - mountPath: /var/www/html/pub/media/catalog
              name: mediadata
      containers:
        - name: nginx
          image: henrytrantdt/magento-nginx:main # TODO: need to patch this image to use the correct tag
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
            - containerPort: 8443
          resources:
            limits:
              cpu: 200m # 1000m = 1CPU core
              memory: 1600Mi # 1000Mi = 1Gi = 1GB of memory
            requests:
              cpu: 100m
              memory: 800Mi
          volumeMounts:
            - name: ssldata
              mountPath: /etc/nginx/certs
              readOnly: true
            - mountPath: /sock
              name: sockdata
            - mountPath: /var/www/html/pub/media/catalog
              name: mediadata
            - mountPath: /var/www/html/auth.json
              subPath: auth.json
              name: composerauth
            - mountPath: /var/www/env.php
              subPath: env.php
              name: appenv
            - mountPath: /var/www/config.php
              subPath: config.php
              name: appconfig
          lifecycle:
            postStart:
              exec:
                command:
                  [
                    "/bin/sh",
                    "-c",
                    "cp /var/www/env.php /var/www/html/app/etc/env.php && cp /var/www/config.php /var/www/html/app/etc/config.php",
                  ]
        - name: phpfpm
          image: henrytrantdt/magento-phpfpm:main # TODO: need to patch this image to use the correct tag
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 400m # 1000m = 1CPU core
              memory: 3200Mi # 1000Mi = 1Gi = 1GB of memory
            requests:
              cpu: 200m
              memory: 1600Mi
          volumeMounts:
            - mountPath: /sock
              name: sockdata
            - mountPath: /var/www/html/pub/media/catalog
              name: mediadata
            - mountPath: /var/www/html/auth.json
              subPath: auth.json
              name: composerauth
            - mountPath: /var/www/env.php
              subPath: env.php
              name: appenv
            - mountPath: /var/www/config.php
              subPath: config.php
              name: appconfig
          lifecycle:
            postStart:
              exec:
                command:
                  [
                    "/bin/sh",
                    "-c",
                    "cp /var/www/env.php /var/www/html/app/etc/env.php && cp /var/www/config.php /var/www/html/app/etc/config.php",
                  ]
          env:
            - name: BLACKFIRE_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: BLACKFIRE_CLIENT_ID
                  name: env-phpfpm-env
            - name: BLACKFIRE_CLIENT_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: BLACKFIRE_CLIENT_TOKEN
                  name: env-phpfpm-env
            - name: COMPOSER_DISABLE_XDEBUG_WARN
              valueFrom:
                configMapKeyRef:
                  key: COMPOSER_DISABLE_XDEBUG_WARN
                  name: env-phpfpm-env
            - name: PHP_CS_FIXER_IGNORE_ENV
              valueFrom:
                configMapKeyRef:
                  key: PHP_CS_FIXER_IGNORE_ENV
                  name: env-phpfpm-env
      restartPolicy: Always
      volumes:
        - name: sockdata
          emptyDir: {}
        - name: mediadata
          persistentVolumeClaim:
            claimName: mediadata
        - name: ssldata
          configMap:
            defaultMode: 0400
            name: ssldata
            items:
              - key: sslcert
                path: nginx.crt
              - key: sslkey
                path: nginx.key
        - name: composerauth
          configMap:
            name: composerauth
            defaultMode: 0640
            items:
              - key: auth
                path: auth.json
        - name: appconfig
          configMap:
            name: appconfig
            defaultMode: 0640
            items:
              - key: config
                path: config.php
        - name: appenv
          configMap:
            name: appenv
            defaultMode: 0640
            items:
              - key: env
                path: env.php
