apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: db
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
        - args:
            - --max_allowed_packet=64M
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: env-db-env
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_HOST
                  name: env-db-env
            - name: MYSQL_INTEGRATION_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_INTEGRATION_DATABASE
                  name: env-db-env
            - name: MYSQL_INTEGRATION_HOST
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_INTEGRATION_HOST
                  name: env-db-env
            - name: MYSQL_INTEGRATION_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_INTEGRATION_PASSWORD
                  name: env-db-env
            - name: MYSQL_INTEGRATION_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_INTEGRATION_ROOT_PASSWORD
                  name: env-db-env
            - name: MYSQL_INTEGRATION_USER
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_INTEGRATION_USER
                  name: env-db-env
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_PASSWORD
                  name: env-db-env
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: env-db-env
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_USER
                  name: env-db-env
          image: mariadb:10.4
          name: db
          ports:
            - containerPort: 3306
          resources: 
            limits:
              cpu: 1000m # 1CPU core
              memory: 2Gi # 2GB of memory
            requests:
              cpu: 500m
              memory: 1Gi     
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: dbdata
      restartPolicy: Always
      volumes:
        - name: dbdata
          persistentVolumeClaim:
            claimName: dbdata
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: dbdata
  name: dbdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
