apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mailcatcher
  name: mailcatcher
spec:
  ports:
    - name: "1080"
      port: 1080
      targetPort: 1080
  selector:
    io.kompose.service: mailcatcher
status:
  loadBalancer: {}
