apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mailcatcher
  name: mailcatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mailcatcher
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: mailcatcher
    spec:
      containers:
        - image: sj26/mailcatcher
          name: mailcatcher
          ports:
            - containerPort: 1080
          resources: {}
      restartPolicy: Always
status: {}
