apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
    reloader.stakater.com/auto: "true"    
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: PHP_DATE_TIMEZONE
              value: EST
            - name: PHP_DISPLAY_ERRORS
              value: "1"
            - name: PHP_MAX_EXECUTION_TIME
              value: "300"
            - name: PHP_MEMORY_LIMIT
              value: 2048M
            - name: PHP_POST_MAX_SIZE
              value: 500M
            - name: PHP_UPLOAD_MAX_FILESIZE
              value: 1024M
            - name: WEB_ALIAS_DOMAIN
              value: local.domain.com
            - name: WEB_DOCUMENT_ROOT
              value: /var/www/html/pub
          image: webdevops/php-nginx:8.1
          name: web
          ports:
            - containerPort: 8888
            - containerPort: 443
            - containerPort: 22
          resources: {}
          volumeMounts:
            - mountPath: /var/www/html
              name: web-claim0
            - name: nginx-config
              mountPath: /opt/docker/etc/nginx/conf.d
      restartPolicy: Always
      volumes:
        - name: web-claim0
          hostPath:
            path: /tmp/web2
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
            - key: config
              path: magento.conf            
status: {}
