apiVersion: v1
kind: Service
metadata:
  labels:
    app: magento
  name: app
  namespace: magento-dev
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
    - name: "8443"
      port: 8443
      targetPort: 8443
  selector:
    app: magento
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: magento
  name: app
  namespace: magento-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magento
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: magento
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      initContainers:
        - name: init
          image: alpine:3
          command: ["/bin/sh", "-c"]
          args:
            - touch /var/www/test_chown.txt
              chown 1000:1000 /var/www/test_chown.txt
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /sock
              name: sockdata
            - mountPath: /var/www/html/pub/media
              name: mediadata
      containers:
        - name: nginx
          image: henrytrantdt/magento-nginx:main # TODO: need to patch this image to use the correct tag
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
            - containerPort: 8443
          resources:
            limits:
              cpu: 400m # 1000m = 1CPU core
              memory: 1600Mi # 1000Mi = 1Gi = 1GB of memory
            requests:
              cpu: 200m
              memory: 800Mi
          volumeMounts:
            - name: ssldata
              mountPath: /etc/nginx/certs
              readOnly: true
            - mountPath: /sock
              name: sockdata
            - mountPath: /var/www/html/pub/media
              name: mediadata
            - mountPath: /var/www/html/auth.json
              subPath: auth.json
              name: composerauth
            - mountPath: /var/www/env.php
              subPath: env.php
              name: appenv
            - mountPath: /var/www/config.php
              subPath: config.php
              name: appconfig
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf         
          lifecycle:
            postStart:
              exec:
                command:
                  [
                    "/bin/sh",
                    "-c",
                    "cp -rf /var/www/env.php /var/www/html/app/etc/env.php && cp -rf /var/www/config.php /var/www/html/app/etc/config.php",
                  ]
        - name: phpfpm
          image: henrytrantdt/magento-phpfpm:main # TODO: need to patch this image to use the correct tag
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m # 1000m = 1CPU core
              memory: 4000Mi # 1000Mi = 1Gi = 1GB of memory
            requests:
              cpu: 500m
              memory: 2000Mi
          volumeMounts:
            - mountPath: /sock
              name: sockdata
            - mountPath: /var/www/html/pub/media
              name: mediadata
            - mountPath: /var/www/html/auth.json
              subPath: auth.json
              name: composerauth
            - mountPath: /var/www/env.php
              subPath: env.php
              name: appenv
            - mountPath: /var/www/config.php
              subPath: config.php
              name: appconfig
          lifecycle:
            postStart:
              exec:
                command:
                  [
                    "/bin/sh",
                    "-c",
                    "cp -rf /var/www/env.php /var/www/html/app/etc/env.php && cp -rf /var/www/config.php /var/www/html/app/etc/config.php",
                  ]
          env:
            - name: BLACKFIRE_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: BLACKFIRE_CLIENT_ID
                  name: env-phpfpm-env
            - name: BLACKFIRE_CLIENT_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: BLACKFIRE_CLIENT_TOKEN
                  name: env-phpfpm-env
            - name: COMPOSER_DISABLE_XDEBUG_WARN
              valueFrom:
                configMapKeyRef:
                  key: COMPOSER_DISABLE_XDEBUG_WARN
                  name: env-phpfpm-env
            - name: PHP_CS_FIXER_IGNORE_ENV
              valueFrom:
                configMapKeyRef:
                  key: PHP_CS_FIXER_IGNORE_ENV
                  name: env-phpfpm-env
      restartPolicy: Always
      volumes:
        - name: sockdata
          emptyDir: {}
        - name: mediadata
          persistentVolumeClaim:
            claimName: mediadata
        - name: ssldata
          configMap:
            defaultMode: 0400
            name: ssldata
            items:
              - key: sslcert
                path: nginx.crt
              - key: sslkey
                path: nginx.key
        - name: composerauth
          configMap:
            name: composerauth
            defaultMode: 0640
            items:
              - key: auth
                path: auth.json
        - name: appconfig
          configMap:
            name: appconfig
            defaultMode: 0640
            items:
              - key: config
                path: config.php
        - name: appenv
          configMap:
            name: appenv
            defaultMode: 0640
            items:
              - key: env
                path: env.php
        - name: nginx-conf
          configMap:
            name: nginx-conf
            defaultMode: 0640
            items:
              - key: default.conf
                path: default.conf
              - key: nginx.conf
                path: nginx.conf
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: app
  namespace: magento-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 50
          periodSeconds: 15
        - type: Pods
          value: 2
          periodSeconds: 15
      selectPolicy: Max
