apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: magento-dev
spec:
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    app: redis
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
  namespace: magento-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy: {}
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: redis:6.2-alpine
          name: redis
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: 200m # 1000m = 1CPU core
              memory: 1600Mi # 1000Mi = 1Gi = 1GB of memory
            requests:
              cpu: 100m
              memory: 800Mi
      restartPolicy: Always
