apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deploy
  name: nginx-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deploy
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app:  nginx-deploy
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq-deploy
  name: rabbitmq-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rabbitmq-deploy
  template:
    metadata:
      labels:
        app: rabbitmq-deploy
    spec:
      containers:
      - image: rabbitmq:3-management
        name: rabbitmq

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: NodePort
  selector:
    app:  rabbitmq-deploy
  ports:
  - name: rmq-admin
    protocol: TCP
    port: 15672
    targetPort: 15672