region          = "ap-southeast-1"
bastion_ami     = "ami-0c802847a7dd848c0"
org             = "org"
division        = "devops"
app             = "m2"
env             = "dev"
vpc_cidr        = "10.0.0.0/16"
ng_ssh_key      = "terraform"
bastion_ssh_key = "terraform"
ami_type        = "AL2_x86_64"
instance_types  = ["t2.medium", "t3.medium"]
capacity_type   = "SPOT"
kube_version    = "1.21"
ng_desired_size = 1
ng_max_size     = 3
ng_min_size     = 1